In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [2]:
df = pd.read_csv("personal-play-records.csv")

print(df.head())
print(df.info())
print(df.describe())

   Episode                   Mission  ... Perfect Stealth, No Kills Bonus Total
0        0       Prologue: Awakening  ...                         0           0
1        1             Phantom Limbs  ...                         0        6000
2        3              A Hero's Way  ...                     20000       50000
3        4                       C2W  ...                         0       10000
4        6  Where do the bees sleep?  ...                         0       74333

[5 rows x 35 columns]
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 35 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Episode                    8 non-null      int64
 1   Mission                    8 non-null      str  
 2   Date                       8 non-null      str  
 3   Score                      8 non-null      str  
 4   Codename                   8 non-null      str  
 5   Rank                    

In [3]:
df = df.dropna()   # simple approach (you can improve later)

In [6]:
# Clean column names (fix hidden spaces)
df.columns = df.columns.str.strip()

# Inspect columns (do this once if unsure)
print(df.columns)



Index(['Episode', 'Mission', 'Date', 'Score', 'Codename', 'Rank', 'Time',
       'T Score', 'Enemy Combat Alerts', 'ECA Score', 'Hits Taken', 'HT Score',
       'Tactical Takedowns', 'TT Score', 'Headshots', 'H Score', 'Accuracy',
       'A Score', 'Neutralizations', 'N Score', 'Markings', 'M Score',
       'Effective Interrogations', 'EI Score', 'Prisoners Rescued', 'PR Score',
       'Play Total', '---', '---.1', 'No Retries', 'No Kills', 'No Reflex',
       'No Enemy Combat Alerts', 'Perfect Stealth, No Kills', 'Bonus Total'],
      dtype='str')


In [7]:
print(df.columns)

Index(['Episode', 'Mission', 'Date', 'Score', 'Codename', 'Rank', 'Time',
       'T Score', 'Enemy Combat Alerts', 'ECA Score', 'Hits Taken', 'HT Score',
       'Tactical Takedowns', 'TT Score', 'Headshots', 'H Score', 'Accuracy',
       'A Score', 'Neutralizations', 'N Score', 'Markings', 'M Score',
       'Effective Interrogations', 'EI Score', 'Prisoners Rescued', 'PR Score',
       'Play Total', '---', '---.1', 'No Retries', 'No Kills', 'No Reflex',
       'No Enemy Combat Alerts', 'Perfect Stealth, No Kills', 'Bonus Total'],
      dtype='str')


In [10]:
from sklearn.datasets import load_iris

data = load_iris()
X = data.data
y = data.target

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# -------------------------
# Step 1: Define features and target
# -------------------------
# Replace this with your actual dataset variables
# X = features, y = target

# Example:
# X = df.drop("target_column", axis=1)
# y = df["target_column"]

# -------------------------
# Step 2: Train-test split
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# -------------------------
# Step 3: Model
# -------------------------
et_model = ExtraTreesClassifier(
    n_estimators=100,
    random_state=42
)

et_model.fit(X_train, y_train)

# -------------------------
# Step 4: Prediction
# -------------------------
et_pred = et_model.predict(X_test)

# -------------------------
# Step 5: Evaluation
# -------------------------
print("🌳 Extra Trees Accuracy:", accuracy_score(y_test, et_pred))
print(confusion_matrix(y_test, et_pred))
print(classification_report(y_test, et_pred))

🌳 Extra Trees Accuracy: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [14]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

rf_model = RandomForestClassifier(random_state=42)
et_model = ExtraTreesClassifier(random_state=42)

rf_model.fit(X_train, y_train)
et_model.fit(X_train, y_train)

rf_importance = rf_model.feature_importances_
et_importance = et_model.feature_importances_

In [16]:
from sklearn.metrics import accuracy_score

# Make predictions (this is what was missing)
rf_pred = rf_model.predict(X_test)
et_pred = et_model.predict(X_test)

# Build results table
results = pd.DataFrame({
    "Model": ["Random Forest", "Extra Trees"],
    "Accuracy": [
        accuracy_score(y_test, rf_pred),
        accuracy_score(y_test, et_pred)
    ]
})

print(results)

           Model  Accuracy
0  Random Forest       1.0
1    Extra Trees       1.0
