In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("top5050words.csv")

# View dataset
print(df.head())
print(df.columns)

  Word
0  the
1   to
2  and
3   of
4    a
Index(['Word'], dtype='str')


In [4]:
if target_column in df.columns:
    X = df.drop(columns=[target_column])
    y = df[target_column]
else:
    print(f"{target_column} not found. Available columns: {df.columns.tolist()}")

label not found. Available columns: ['Word']


In [5]:
print("label" in df.columns)

False


In [9]:
df.head()

,Word
0,the
1,to
2,and
3,of
4,a


In [12]:
from sklearn.datasets import load_iris
import pandas as pd

data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df["target"] = data.target

In [15]:
# Example dataset split
X = df.drop("target", axis=1)
y = df["target"]

from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

et_model = ExtraTreesClassifier(
    n_estimators=200,
    random_state=42
)

et_model.fit(X_train, y_train)
et_pred = et_model.predict(X_test)

print("🌳 Extra Trees Accuracy:", accuracy_score(y_test, et_pred))
print(classification_report(y_test, et_pred))

🌳 Extra Trees Accuracy: 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [18]:
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.metrics import confusion_matrix

# Train Random Forest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

# Train Extra Trees
et = ExtraTreesClassifier()
et.fit(X_train, y_train)
et_pred = et.predict(X_test)

# Confusion matrices
print("Random Forest Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

print("\nExtra Trees Confusion Matrix:")
print(confusion_matrix(y_test, et_pred))

Random Forest Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Extra Trees Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [21]:
print([name for name in globals() if "vector" in name.lower()])

[]
